apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-xcah
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-xcah@sha256:a047a412801a874be0ddf08002f6367bf0ee6a15ea8a10df72f52700394842d2
        name: my-python
        resources: {}
status: {}
