apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-88av
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-88av@sha256:b317755d46cd045b538dae563c26c88bc0f36a7f48ba0a134aade78794292afd
        name: my-nodejs
        resources: {}
status: {}
